<?php

/*
* Project: CTRL-WebAdmin
* Author: Muris Pucic Trax <trax [AT] elektronika [DOT] ba>
* Version: 1.0
*/

$BAD_EMAIL_DOMAINS = array(
	'0-MAIL.COM',
	'10MINUTEMAIL.COM',
	'30MINUTEMAIL.COM',
	'4WARDING.NET',
	'AMILEGIT.COM',
	'ANTISPAM.DE',
	'BIO-MUESLI.NET',
	'BOOTYBAY.DE',
	'BUGMENOT.COM',
	'COURRIELTEMPORAIRE.COM',
	'CUST.IN',
	'DAYREP.COM',
	'DEVNULLMAIL.COM',
	'DISPOSEMAIL.COM',
	'DODGIT.COM',
	'DONEMAIL.RU',
	'DRDRB.NET',
	'E4WARD.COM',
	'EMAILINFIVE.COM',
	'EMAILTEMPORARIO.COM.BR',
	'EVOPO.COM',
	'FASTACURA.COM',
	'FR33MAIL.INFO',
	'GETONEMAIL.COM',
	'GREAT-HOST.IN',
	'GUERRILLAMAILBLOCK.COM',
	'HOCHSITZE.COM',
	'IEATSPAM.EU',
	'IMAILS.INFO',
	'INCOGNITOMAIL.ORG',
	'JETABLE.COM',
	'JNXJN.COM',
	'KIR.CH.TC',
	'LHSDV.COM',
	'LOOKUGLY.COM',
	'MAIL-TEMPORAIRE.FR',
	'MAILCATCH.COM',
	'MAILIMATE.COM',
	'MAILINATOR.NET',
	'MAILMATE.COM',
	'MAILMETRASH.COM',
	'MAILNULL.COM',
	'MAILZILLA.ORG',
	'MESSAGEBEAMER.DE',
	'MOBURL.COM',
	'MT2009.COM',
	'MYTRASHMAIL.COM',
	'NOBULK.COM',
	'NOMAIL2ME.COM',
	'NOSPAMFOR.US',
	'NOWMYMAIL.COM',
	'ONEWAYMAIL.COM',
	'OVPN.TO',
	'PLEXOLAN.DE',
	'PRTNX.COM',
	'RECODE.ME',
	'RPPKN.COM',
	'SAFE-MAIL.NET',
	'SANDELF.DE',
	'SENDSPAMHERE.COM',
	'SKEEFMAIL.COM',
	'SNAKEMAIL.COM',
	'SOGETTHIS.COM',
	'SPAMAVERT.COM',
	'SPAMBOG.COM',
	'SPAMBOG.RU',
	'SPAMBOX.US',
	'SPAMFREE24.COM',
	'SPAMFREE24.INFO',
	'SPAMGOURMET.COM',
	'SPAMIFY.COM',
	'SPAML.COM',
	'SPAMOBOX.COM',
	'SPAMTHISPLEASE.COM',
	'SUREMAIL.INFO',
	'TELEWORM.US',
	'TEMPEMAIL.BIZ',
	'TEMPINBOX.CO.UK',
	'TEMPMAIL2.COM',
	'TEMPORARYEMAIL.NET',
	'THANKYOU2010.COM',
	'TMAILINATOR.COM',
	'TRASH-AMIL.COM',
	'TRASH2009.COM',
	'TRASHMAIL.COM',
	'TRASHMAILER.COM',
	'TRILLIANPRO.COM',
	'VERYREALEMAIL.COM',
	'WH4F.ORG',
	'WUZUPMAIL.NET',
	'ZEHNMINUTENMAIL.DE',
	'0815.RU',
	'20MINUTEMAIL.COM',
	'3D-PAINTING.COM',
	'4WARDING.ORG',
	'ANONBOX.NET',
	'BEEFMILK.COM',
	'BOBMAIL.INFO',
	'BREFMAIL.COM',
	'BUMPYMAIL.COM',
	'CUBICLINK.COM',
	'DACOOLEST.COM',
	'DEADADDRESS.COM',
	'DISCARDMAIL.COM',
	'DISPOSTABLE.COM',
	'DODGIT.ORG',
	'DONTREG.COM',
	'DUMP-EMAIL.INFO',
	'EMAIL60.COM',
	'EMAILMISER.COM',
	'EMAILWARDEN.COM',
	'FAKEINBOX.COM',
	'FILZMAIL.COM',
	'GET1MAIL.COM',
	'GETONEMAIL.NET',
	'GUERILLAMAIL.COM',
	'H.MINTEMAIL.COM',
	'HOTPOP.COM',
	'IEATSPAM.INFO',
	'INCOGNITOMAIL.COM',
	'INSORG-MAIL.INFO',
	'JETABLE.NET',
	'JUNK1E.COM',
	'KLZLK.COM',
	'LITEDROP.COM',
	'LOPL.CO.CC',
	'MAIL.BY',
	'MAILEATER.COM',
	'MAILIN8R.COM',
	'MAILINATOR2.COM',
	'MAILME.IR',
	'MAILNATOR.COM',
	'MAILSLITE.COM',
	'MBX.CC',
	'MIERDAMAIL.COM',
	'MONEMAIL.FR.NF',
	'MYPARTYCLIP.DE',
	'NEPWK.COM',
	'NOCLICKEMAIL.COM',
	'NOMORESPAMEMAILS.COM',
	'NOSPAMTHANKS.INFO',
	'NUS.EDU.SG',
	'ONLINE.MS',
	'OWLPIC.COM',
	'POLITIKERCLUB.DE',
	'QQ.COM',
	'REGBYPASS.COM',
	'RTRTR.COM',
	'SAFETYMAIL.INFO',
	'SAYNOTOSPAMS.COM',
	'SHARKLASERS.COM',
	'SLOPSBOX.COM',
	'SOFIMAIL.COM',
	'SPAM.LA',
	'SPAMBOB.NET',
	'SPAMBOG.DE',
	'SPAMBOX.INFO',
	'SPAMCERO.COM',
	'SPAMFREE24.DE',
	'SPAMFREE24.NET',
	'SPAMHERELOTS.COM',
	'SPAMINATOR.DE',
	'SPAML.DE',
	'SPAMSPOT.COM',
	'SUPERGREATMAIL.COM',
	'TEEWARS.ORG',
	'TEMPALIAS.COM',
	'TEMPEMAIL.COM',
	'TEMPINBOX.COM',
	'TEMPOMAIL.FR',
	'TEMPORARYINBOX.COM',
	'THISISNOTMYREALEMAIL.COM',
	'TOIEA.COM',
	'TRASH-MAIL.COM',
	'TRASHEMAIL.DE',
	'TRASHMAIL.NET',
	'TRASHYMAIL.COM',
	'TYLDD.COM',
	'WEBM4IL.INFO',
	'WHYSPAM.ME',
	'YOPMAIL.COM',
	'ZIPPYMAIL.INFO',
	'0CLICKEMAIL.COM',
	'2PRONG.COM',
	'4WARDING.COM',
	'60MINUTEMAIL.COM',
	'ANONYMBOX.COM',
	'BINKMAIL.COM',
	'BOFTHEW.COM',
	'BSNOW.NET',
	'COSMORPH.COM',
	'CURRYWORLD.DE',
	'DANDIKMAIL.COM',
	'DESPAM.IT',
	'DISCARDMAIL.DE',
	'DODGEIT.COM',
	'DOIEA.COM',
	'DONTSENDMESPAM.DE',
	'DUMPYEMAIL.COM',
	'EMAILIGO.DE',
	'EMAILSENSEI.COM',
	'EMAILX.AT.HM',
	'FAKEINFORMATION.COM',
	'FIZMAIL.COM',
	'GET2MAIL.FR',
	'GISHPUPPY.COM',
	'GUERRILLAMAIL.COM',
	'HALTOSPAM.COM',
	'HULAPLA.DE',
	'IEH-MAIL.DE',
	'INCOGNITOMAIL.NET',
	'IPOO.ORG',
	'JETABLE.ORG',
	'KEEPMYMAIL.COM',
	'KULTURBETRIEB.INFO',
	'LOL.OVPN.TO',
	'M4ILWEB.INFO',
	'MAIL4TRASH.COM',
	'MAILEXPIRE.COM',
	'MAILINATOR.COM',
	'MAILISMAGIC.COM',
	'MAILME.LV',
	'MAILNESIA.COM',
	'MAILTEMP.INFO',
	'MELTMAIL.COM',
	'MINTEMAIL.COM',
	'MSA.MINSMAIL.COM',
	'MYPHANTOMEMAIL.COM',
	'NO-SPAM.WS',
	'NOGMAILSPAM.INFO',
	'NOSPAM4.US',
	'NOTMAILINATOR.COM',
	'NWLDX.COM',
	'OPAYQ.COM',
	'PJJKP.COM',
	'POOKMAIL.COM',
	'QUICKINBOX.COM',
	'RMQKR.NET',
	'S0NY.NET',
	'SAFETYPOST.DE',
	'SELFDESTRUCTINGMAIL.COM',
	'SHITMAIL.ME',
	'SMELLFEAR.COM',
	'SOFORT-MAIL.DE',
	'SPAM.SU',
	'SPAMBOB.ORG',
	'SPAMBOG.NET',
	'SPAMBOX.IRISHSPRINGREALTY.COM',
	'SPAMDAY.COM',
	'SPAMFREE24.EU',
	'SPAMFREE24.ORG',
	'SPAMHOLE.COM',
	'SPAMKILL.INFO',
	'SPAMMOTEL.COM',
	'SPAMTHIS.CO.UK',
	'SUPERMAILER.JP',
	'TELEWORM.COM',
	'TEMPE-MAIL.COM',
	'TEMPEMAIL.NET',
	'TEMPMAIL.IT',
	'TEMPORARIOEMAIL.COM.BR',
	'THANKSNOSPAM.INFO',
	'THROWAWAYEMAILADDRESS.COM',
	'TRADERMAIL.INFO',
	'TRASH-MAIL.DE',
	'TRASHMAIL.AT',
	'TRASHMAIL.WS',
	'TRASHYMAIL.NET',
	'UGGSROCK.COM',
	'WEGWERFEMAIL.DE',
	'WILLSELFDESTRUCT.COM',
	'YUUROK.COM',
	'ZOAXE.COM',
);

// add missing requiredvars into formvars
function fixFormVars(&$formvars, $requiredvars) {
	if(count($requiredvars)<=0) return;

	for($i=0; $i<count($requiredvars); $i++) {
		if(!array_key_exists($requiredvars[$i], $formvars)) {
			$formvars[$requiredvars[$i]] = '';
		}
	}
}

function randomHex($length) {
    $alphabet = "0123456789abcdef";
    $pass = array(); // remember to declare $pass as an array
    $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
    for ($i = 0; $i < $length; $i++) {
        $n = rand(0, $alphaLength);
        $pass[] = $alphabet[$n];
    }
    return implode($pass); // turn the array into a string
}

//http://stackoverflow.com/questions/6101956/generating-a-random-password-in-php
function randomPassword($length) {
    $alphabet = "abcdefghijklmnpqrstuwxyzABCDEFGHJKLMNPQRSTUWXYZ123456789";
    $pass = array(); // remember to declare $pass as an array
    $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
    for ($i = 0; $i < $length; $i++) {
        $n = rand(0, $alphaLength);
        $pass[] = $alphabet[$n];
    }
    return implode($pass); // turn the array into a string
}

function sendMail($to_email, $subject, $message) {
	// Custom header
	$hh ="Reply-to: <nobody@ctrl.ba>\n";
	$hh.="From: <nobody@ctrl.ba>\n";
	$hh.="Return-path: <nobody@ctrl.ba>\n";
	$hh.="Message-ID: <".md5(uniqid(time()))."@"."ctrl.ba".">\n";
	$hh.="MIME-Version: 1.0\n";
	$hh.="Content-Type: text/plain; charset=UTF-8\n";
	$hh.="Content-transfer-encoding: 8bit\n";
	$hh.="Date: " . date('r', time()) . "\n";
	$hh.="X-Priority: 3\n";
	$hh.="X-MSMail-Priority: Normal\n";
	$hh.="X-Mailer: PHP\n";
	$hh.="X-MimeOLE: Produced By Trax from Elektronika.ba\n";

	// Send!
	return @mail($to_email, $subject, $message, $hh);
}

?>